
<div id="header-box">
    <div id="module-menu">
        <ul id="menu" >
            <li class="node"><a href="#">Site</a><ul>
                    <li><a class="icon-16-cpanel" href="index.php">Control Panel</a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-profile" href="index.php?option=com_admin&amp;task=profile.edit&amp;id=42">My Profile</a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-config" href="index.php?option=com_config">Global Configuration</a></li>

                    <li class="separator"><span></span></li>
                    <li class="node"><a class="icon-16-maintenance" href="index.php?option=com_checkin">Maintenance</a><ul id="menu-com-checkin" class="menu-component">
                            <li><a class="icon-16-checkin" href="index.php?option=com_checkin">Global Check-in</a></li>
                            <li class="separator"><span></span></li>
                            <li><a class="icon-16-clear" href="index.php?option=com_cache">Clear Cache</a></li>
                            <li><a class="icon-16-purge" href="index.php?option=com_cache&amp;view=purge">Purge Expired Cache</a></li>
                        </ul>
                    </li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-info" href="index.php?option=com_admin&amp;view=sysinfo">System Information</a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-logout" href="/administrator/index.php?option=com_login&amp;task=logout&amp;c978cef3fefdcfc5320d05e605203080=1">Logout</a></li>

                </ul>
            </li>
            <li class="node"><a href="#">Users</a><ul>
                    <li class="node"><a class="icon-16-user" href="index.php?option=com_users&amp;view=users">User Manager</a><ul id="menu-com-users-users" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_users&amp;task=user.add">Add New User</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-groups" href="index.php?option=com_users&amp;view=groups">Groups</a><ul id="menu-com-users-groups" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_users&amp;task=group.add">Add New Group</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-levels" href="index.php?option=com_users&amp;view=levels">Access Levels</a><ul id="menu-com-users-levels" class="menu-component">

                            <li><a class="icon-16-newarticle" href="index.php?option=com_users&amp;task=level.add">Add New Access Level</a></li>
                        </ul>
                    </li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-massmail" href="index.php?option=com_users&amp;view=mail">Mass Mail Users</a></li>
                </ul>
            </li>
            <li class="node"><a href="#">Menus</a><ul>
                    <li class="node"><a class="icon-16-menumgr" href="index.php?option=com_menus&amp;view=menus">Menu Manager</a><ul id="menu-com-menus-menus" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_menus&amp;view=menu&amp;layout=edit">Add New Menu</a></li>
                        </ul>
                    </li>

                    <li class="separator"><span></span></li>
                    <li class="node"><a class="icon-16-menu" href="index.php?option=com_menus&amp;view=items&amp;menutype=usermenu">User Menu</a><ul id="menu-com-menus-items-usermenu" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype=usermenu">Add New Menu Item</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-menu" href="index.php?option=com_menus&amp;view=items&amp;menutype=top">Top</a><ul id="menu-com-menus-items-top" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype=top">Add New Menu Item</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-menu" href="index.php?option=com_menus&amp;view=items&amp;menutype=aboutjoomla">About Joomla</a><ul id="menu-com-menus-items-aboutjoomla" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype=aboutjoomla">Add New Menu Item</a></li>

                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-menu" href="index.php?option=com_menus&amp;view=items&amp;menutype=parks">Australian Parks</a><ul id="menu-com-menus-items-parks" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype=parks">Add New Menu Item</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-menu" href="index.php?option=com_menus&amp;view=items&amp;menutype=mainmenu">Main Menu <span><img src="/administrator/templates/bluestork/images/menu/icon-16-default.png" alt="*" title="Home" /></span></a><ul id="menu-com-menus-items-mainmenu" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype=mainmenu">Add New Menu Item</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-menu" href="index.php?option=com_menus&amp;view=items&amp;menutype=fruitshop">Fruit Shop</a><ul id="menu-com-menus-items-fruitshop" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype=fruitshop">Add New Menu Item</a></li>

                        </ul>
                    </li>
                </ul>
            </li>
            <li class="node"><a href="#">Content</a><ul>
                    <li class="node"><a class="icon-16-article" href="index.php?option=com_content">Article Manager</a><ul id="menu-com-content" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_content&amp;task=article.add">Add New Article</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-category" href="index.php?option=com_categories&amp;extension=com_content">Category Manager</a><ul id="menu-com-categories-com-content" class="menu-component">
                            <li><a class="icon-16-newarticle" href="index.php?option=com_categories&amp;task=category.add&amp;extension=com_content">Add New Category</a></li>
                        </ul>

                    </li>
                    <li><a class="icon-16-featured" href="index.php?option=com_content&amp;view=featured">Featured Articles</a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-media" href="index.php?option=com_media">Media Manager</a></li>
                </ul>
            </li>
            <li class="node"><a href="#">Components</a><ul>
                    <li class="node"><a class="icon-16-banners" href="index.php?option=com_banners">Banners</a><ul id="menu-com-banners" class="menu-component">
                            <li><a class="icon-16-banners" href="index.php?option=com_banners">Banners</a></li>
                            <li><a class="icon-16-banners-cat" href="index.php?option=com_categories&amp;extension=com_banners">Categories</a></li>
                            <li><a class="icon-16-banners-clients" href="index.php?option=com_banners&amp;view=clients">Clients</a></li>

                            <li><a class="icon-16-banners-tracks" href="index.php?option=com_banners&amp;view=tracks">Tracks</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-contact" href="index.php?option=com_contact">Contacts</a><ul id="menu-com-contact" class="menu-component">
                            <li><a class="icon-16-contact" href="index.php?option=com_contact">Contacts</a></li>
                            <li><a class="icon-16-contact-cat" href="index.php?option=com_categories&amp;extension=com_contact">Categories</a></li>
                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-messages" href="index.php?option=com_messages">Messaging</a><ul id="menu-com-messages" class="menu-component">
                            <li><a class="icon-16-messages-add" href="index.php?option=com_messages&amp;task=message.add">New Private Message</a></li>
                            <li><a class="icon-16-messages-read" href="index.php?option=com_messages">Read Private Messages</a></li>

                        </ul>
                    </li>
                    <li class="node"><a class="icon-16-newsfeeds" href="index.php?option=com_newsfeeds">Newsfeeds</a><ul id="menu-com-newsfeeds" class="menu-component">
                            <li><a class="icon-16-newsfeeds" href="index.php?option=com_newsfeeds">Feeds</a></li>
                            <li><a class="icon-16-newsfeeds-cat" href="index.php?option=com_categories&amp;extension=com_newsfeeds">Categories</a></li>
                        </ul>
                    </li>
                    <li><a class="icon-16-redirect" href="index.php?option=com_redirect">Redirect</a></li>
                    <li><a class="icon-16-search" href="index.php?option=com_search">Search</a></li>
                    <li class="node"><a class="icon-16-weblinks" href="index.php?option=com_weblinks">Weblinks</a><ul id="menu-com-weblinks" class="menu-component">
                            <li><a class="icon-16-weblinks" href="index.php?option=com_weblinks">Links</a></li>

                            <li><a class="icon-16-weblinks-cat" href="index.php?option=com_categories&amp;extension=com_weblinks">Categories</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="node"><a href="#">Extensions</a><ul>
                    <li><a class="icon-16-install" href="index.php?option=com_installer">Extension Manager</a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-module" href="index.php?option=com_modules">Module Manager</a></li>
                    <li><a class="icon-16-plugin" href="index.php?option=com_plugins">Plug-in Manager</a></li>
                    <li><a class="icon-16-themes" href="index.php?option=com_templates">Template Manager</a></li>

                    <li><a class="icon-16-language" href="index.php?option=com_languages">Language Manager</a></li>
                </ul>
            </li>
            <li class="node"><a href="#">Help</a><ul>
                    <li><a class="icon-16-help" href="index.php?option=com_admin&amp;view=help">Joomla Help</a></li>
                    <li class="separator"><span></span></li>
                    <li><a class="icon-16-help-forum" href="http://forum.joomla.org" target="_blank" >Official Support Forum</a></li>
                    <li><a class="icon-16-help-docs" href="http://docs.joomla.org" target="_blank" >Documentation Wiki</a></li>
                    <li class="separator"><span></span></li>
                    <li class="node"><a class="icon-16-weblinks" href="#">Useful Joomla links</a><ul class="menu-component">
                            <li><a class="icon-16-help-jed" href="http://extensions.joomla.org" target="_blank" >Joomla Extensions</a></li>

                            <li><a class="icon-16-help-trans" href="http://community.joomla.org/translations.html" target="_blank" >Joomla Translations</a></li>
                            <li><a class="icon-16-help-jrd" href="http://resources.joomla.org" target="_blank" >Joomla Resources</a></li>
                            <li><a class="icon-16-help-community" href="http://community.joomla.org" target="_blank" >Community Portal</a></li>
                            <li><a class="icon-16-help-security" href="http://developer.joomla.org/security.html" target="_blank" >Security Center</a></li>
                            <li><a class="icon-16-help-dev" href="http://developer.joomla.org" target="_blank" >Developer Resources</a></li>
                            <li><a class="icon-16-help-shop" href="http://shop.joomla.org" target="_blank" >Joomla Shop</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>

    </div>
    <div id="module-status">
        <span class="loggedin-users">None Logged-in frontend</span><span class="backloggedin-users">1 Logged-in backend</span><span class="no-unread-messages"><a href="/administrator/index.php?option=com_messages">No messages</a></span>
        <span class="viewsite"><a href="http://joomla/" target="_blank">View Site</a></span><span class="logout"><a href="/administrator/index.php?option=com_login&amp;task=logout&amp;c978cef3fefdcfc5320d05e605203080=1">Log out</a></span>		</div>
    <div class="clr"></div>

</div>

<div id="content-box">
    <div id="toolbar-box">
        <div class="m">
            <div class="toolbar-list" id="toolbar">
                <ul>
                    <li class="button" id="toolbar-new">
                        <a href="#" onclick="javascript:Joomla.submitbutton('category.add')" class="toolbar">
                            <span class="icon-32-new">
                            </span>
                            New

                        </a>
                    </li>

                    <li class="button" id="toolbar-edit">
                        <a href="#" onclick="javascript:if (document.adminForm.boxchecked.value==0){alert('Please first make a selection from the list');}else{ Joomla.submitbutton('category.edit')}" class="toolbar">
                            <span class="icon-32-edit">
                            </span>
                            Edit
                        </a>
                    </li>

                    <li class="divider">
                    </li>

                    <li class="button" id="toolbar-publish">
                        <a href="#" onclick="javascript:if (document.adminForm.boxchecked.value==0){alert('Please first make a selection from the list');}else{ Joomla.submitbutton('categories.publish')}" class="toolbar">
                            <span class="icon-32-publish">

                            </span>
                            Publish
                        </a>
                    </li>

                    <li class="button" id="toolbar-unpublish">
                        <a href="#" onclick="javascript:if (document.adminForm.boxchecked.value==0){alert('Please first make a selection from the list');}else{ Joomla.submitbutton('categories.unpublish')}" class="toolbar">
                            <span class="icon-32-unpublish">
                            </span>
                            Unpublish
                        </a>
                    </li>

                    <li class="divider">
                    </li>

                    <li class="button" id="toolbar-archive">

                        <a href="#" onclick="javascript:if (document.adminForm.boxchecked.value==0){alert('Please first make a selection from the list');}else{ Joomla.submitbutton('categories.archive')}" class="toolbar">
                            <span class="icon-32-archive">
                            </span>
                            Archive
                        </a>
                    </li>

                    <li class="button" id="toolbar-checkin">
                        <a href="#" onclick="javascript:if (document.adminForm.boxchecked.value==0){alert('Please first make a selection from the list');}else{ Joomla.submitbutton('categories.checkin')}" class="toolbar">
                            <span class="icon-32-checkin">
                            </span>
                            Check In
                        </a>
                    </li>

                    <li class="button" id="toolbar-trash">
                        <a href="#" onclick="javascript:if (document.adminForm.boxchecked.value==0){alert('Please first make a selection from the list');}else{ Joomla.submitbutton('categories.trash')}" class="toolbar">

                            <span class="icon-32-trash">
                            </span>
                            Trash
                        </a>
                    </li>

                    <li class="divider">
                    </li>

                    <li class="button" id="toolbar-refresh">
                        <a href="#" onclick="javascript:Joomla.submitbutton('categories.rebuild')" class="toolbar">
                            <span class="icon-32-refresh">
                            </span>
                            Rebuild
                        </a>
                    </li>

                    <li class="button" id="toolbar-popup-options">
                        <a class="modal" href="http://joomla/administrator/index.php?option=com_config&amp;view=component&amp;component=com_content&amp;path=&amp;tmpl=component" rel="{handler: 'iframe', size: {x: 875, y: 550}, onClose: function() {}}">
                            <span class="icon-32-options">
                            </span>
                            Options
                        </a>
                    </li>

                    <li class="divider">
                    </li>

                    <li class="button" id="toolbar-help">
                        <a href="#" onclick="popupWindow('http://help.joomla.org/proxy/index.php?option=com_help&amp;amp;keyref=Help17:Components_Content_Categories', 'Help', 700, 500, 1)" rel="help" class="toolbar">
                            <span class="icon-32-help">
                            </span>
                            Help
                        </a>

                    </li>

                </ul>
                <div class="clr"></div>
            </div>
            <div class="pagetitle icon-48-categories icon-48-content-categories"><h2>Category Manager: Articles</h2></div>
        </div>
    </div>
    <div id="submenu-box">
        <div class="m">
            <ul id="submenu">

                <li>
                    <a href="index.php?option=com_content&amp;view=articles">Articles</a>	</li>
                <li>
                    <a class="active" href="index.php?option=com_categories&amp;extension=com_content">Categories</a>	</li>
                <li>
                    <a href="index.php?option=com_content&amp;view=featured">Featured Articles</a>	</li>

            </ul>
            <div class="clr"></div>
        </div>
    </div>


    <div id="system-message-container">
    </div>
    <div id="element-box">
        <div class="m">
            <form action="/administrator/index.php?option=com_categories&amp;view=categories" method="post" name="adminForm" id="adminForm">

                <fieldset id="filter-bar">
                    <div class="filter-search fltlft">
                        <label class="filter-search-lbl" for="filter_search">Filter:</label>
                        <input type="text" name="filter_search" id="filter_search" value="" title="Search" />
                        <button type="submit">Search</button>
                        <button type="button" onclick="document.id('filter_search').value='';this.form.submit();">Clear</button>
                    </div>

                    <div class="filter-select fltrt">
                        <select name="filter_level" class="inputbox" onchange="this.form.submit()">
                            <option value="">- Select Max Levels -</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>

                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>

                        <select name="filter_published" class="inputbox" onchange="this.form.submit()">

                            <option value="">- Select Status -</option>
                            <option value="1">Published</option>
                            <option value="0">Unpublished</option>
                            <option value="2">Archived</option>
                            <option value="-2">Trashed</option>
                            <option value="*">All</option>
                        </select>

                        <select name="filter_access" class="inputbox" onchange="this.form.submit()">
                            <option value="">- Select Access -</option>
                            <option value="1">Public</option>
                            <option value="2">Registered</option>
                            <option value="3">Special</option>
                            <option value="4">Customer Access Level (Example)</option>
                        </select>

                        <select name="filter_language" class="inputbox" onchange="this.form.submit()">
                            <option value="">- Select Language -</option>
                            <option value="*">All</option>
                            <option value="en-GB">English (UK)</option>
                        </select>
                    </div>
                </fieldset>
                <div class="clr"> </div>

                <table class="adminlist">
                    <thead>
                        <tr>
                            <th width="1%">
                                <input type="checkbox" name="checkall-toggle" value="" title="Check All" onclick="Joomla.checkAll(this)" />
                            </th>
                            <th>
                                <a href="javascript:tableOrdering('a.title','asc','');" title="Click to sort by this column">Title</a>				</th>

                            <th width="5%">
                                <a href="javascript:tableOrdering('a.published','asc','');" title="Click to sort by this column">Status</a>				</th>
                            <th width="10%">
                                <a href="javascript:tableOrdering('a.lft','desc','');" title="Click to sort by this column">Ordering<img src="/media/system/images/sort_asc.png" alt=""  /></a>											<a href="javascript:saveorder(19, 'categories.saveorder')" class="saveorder" title="Save Order"></a>									</th>
                            <th width="10%">
                                <a href="javascript:tableOrdering('access_level','asc','');" title="Click to sort by this column">Access</a>				</th>

                            <th width="5%" class="nowrap">
                                <a href="javascript:tableOrdering('language','asc','');" title="Click to sort by this column">Language</a>				</th>
                            <th width="1%" class="nowrap">
                                <a href="javascript:tableOrdering('a.id','asc','');" title="Click to sort by this column">ID</a>				</th>
                        </tr>
                    </thead>
                    <tfoot>

                        <tr>
                            <td colspan="15">
                                <div class="container"><div class="pagination">

                                        <div class="limit">Display #<select id="limit" name="limit" class="inputbox" size="1" onchange="Joomla.submitform();">
                                                <option value="5">5</option>
                                                <option value="10">10</option>
                                                <option value="15">15</option>

                                                <option value="20" selected="selected">20</option>
                                                <option value="25">25</option>
                                                <option value="30">30</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                                <option value="0">All</option>

                                            </select>
                                        </div><div class="button2-right off"><div class="start"><span>Start</span></div></div><div class="button2-right off"><div class="prev"><span>Prev</span></div></div>
                                        <div class="button2-left"><div class="page"><span>1</span><a href="#" title="2" onclick="document.adminForm.limitstart.value=20; Joomla.submitform();return false;">2</a>
                                            </div></div><div class="button2-left"><div class="next"><a href="#" title="Next" onclick="document.adminForm.limitstart.value=20; Joomla.submitform();return false;">Next</a></div></div><div class="button2-left"><div class="end"><a href="#" title="End" onclick="document.adminForm.limitstart.value=20; Joomla.submitform();return false;">End</a></div></div>
                                        <div class="limit">Page 1 of 2</div>
                                        <input type="hidden" name="limitstart" value="0" />
                                    </div></div>				</td>
                        </tr>

                    </tfoot>
                    <tbody>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb0" name="cid[]" value="14" onclick="isChecked(this.checked);" title="Checkbox for row 1" />					</td>
                            <td>
                                <a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=14&amp;extension=com_content">
                                    Sample Data-Articles</a>

                                <p class="smallsub" title="sample-data-articles">
                                    (<span>Alias</span>: sample-data-articles)							</p>
                            </td>
                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb0','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">

                                <span>&#160;</span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />
                            </td>
                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>

                            <td class="center">
                                <span title="9-56">
                                    14</span>
                            </td>
                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb1" name="cid[]" value="19" onclick="isChecked(this.checked);" title="Checkbox for row 2" />					</td>

                            <td>
                                <span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=19&amp;extension=com_content">
                                    Joomla!</a>
                                <p class="smallsub" title="sample-data-articles/joomla">
                                    <span class="gtr">|&mdash;</span>															(<span>Alias</span>: joomla)							</p>

                            </td>
                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb1','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span>&#160;</span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb1','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />

                            </td>
                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="10-39">
                                    19</span>

                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb2" name="cid[]" value="20" onclick="isChecked(this.checked);" title="Checkbox for row 3" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=20&amp;extension=com_content">

                                    Extensions</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: extensions)							</p>
                            </td>
                            <td class="center">

                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb2','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span>&#160;</span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />
                            </td>
                            <td class="center">
                                Public					</td>

                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="11-38">
                                    20</span>
                            </td>
                        </tr>
                        <tr class="row1">

                            <td class="center">
                                <input type="checkbox" id="cb3" name="cid[]" value="21" onclick="isChecked(this.checked);" title="Checkbox for row 4" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=21&amp;extension=com_content">
                                    Components</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/components">

                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: components)							</p>
                            </td>
                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb3','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>

                            <td class="order">
                                <span>&#160;</span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb3','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />
                            </td>
                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">

                                All										</td>
                            <td class="center">
                                <span title="12-13">
                                    21</span>
                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">

                                <input type="checkbox" id="cb4" name="cid[]" value="22" onclick="isChecked(this.checked);" title="Checkbox for row 5" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=22&amp;extension=com_content">
                                    Modules</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/modules">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: modules)							</p>

                            </td>
                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb4','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb4','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb4','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="2"  class="text-area-order" />

                            </td>
                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="14-25">
                                    22</span>

                            </td>
                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb5" name="cid[]" value="64" onclick="isChecked(this.checked);" title="Checkbox for row 6" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=64&amp;extension=com_content">

                                    Content Modules</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/modules/articles-modules">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: articles-modules)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb5','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span>&#160;</span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb5','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="15-16">
                                    64</span>

                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb6" name="cid[]" value="65" onclick="isChecked(this.checked);" title="Checkbox for row 7" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=65&amp;extension=com_content">

                                    User Modules</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/modules/user-modules">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: user-modules)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb6','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb6','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb6','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="2"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="17-18">
                                    65</span>

                            </td>
                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb7" name="cid[]" value="66" onclick="isChecked(this.checked);" title="Checkbox for row 8" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=66&amp;extension=com_content">

                                    Display Modules</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/modules/display-modules">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: display-modules)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb7','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb7','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb7','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="3"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="19-20">
                                    66</span>

                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb8" name="cid[]" value="67" onclick="isChecked(this.checked);" title="Checkbox for row 9" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=67&amp;extension=com_content">

                                    Utility Modules</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/modules/utility-modules">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: utility-modules)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb8','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb8','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb8','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="4"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="21-22">
                                    67</span>

                            </td>
                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb9" name="cid[]" value="75" onclick="isChecked(this.checked);" title="Checkbox for row 10" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=75&amp;extension=com_content">

                                    Navigation Modules</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/modules/navigation-modules">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: navigation-modules)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb9','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb9','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="5"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="23-24">
                                    75</span>

                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb10" name="cid[]" value="23" onclick="isChecked(this.checked);" title="Checkbox for row 11" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=23&amp;extension=com_content">

                                    Templates</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/templates">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: templates)							</p>
                            </td>
                            <td class="center">

                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb10','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb10','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb10','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="3"  class="text-area-order" />
                            </td>
                            <td class="center">

                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="26-33">
                                    23</span>
                            </td>

                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb11" name="cid[]" value="69" onclick="isChecked(this.checked);" title="Checkbox for row 12" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=69&amp;extension=com_content">

                                    Beez 20</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/templates/beez-20">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: beez-20)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb11','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span>&#160;</span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb11','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="27-28">
                                    69</span>

                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb12" name="cid[]" value="70" onclick="isChecked(this.checked);" title="Checkbox for row 13" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=70&amp;extension=com_content">

                                    Beez5</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/templates/beez5">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: beez5)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb12','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb12','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb12','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="2"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="29-30">
                                    70</span>

                            </td>
                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb13" name="cid[]" value="68" onclick="isChecked(this.checked);" title="Checkbox for row 14" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=68&amp;extension=com_content">

                                    Atomic</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/templates/atomic">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: atomic)							</p>
                            </td>

                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb13','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb13','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="3"  class="text-area-order" />
                            </td>

                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="31-32">
                                    68</span>

                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb14" name="cid[]" value="24" onclick="isChecked(this.checked);" title="Checkbox for row 15" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=24&amp;extension=com_content">

                                    Languages</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/languages">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: languages)							</p>
                            </td>
                            <td class="center">

                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb14','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb14','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb14','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="4"  class="text-area-order" />
                            </td>
                            <td class="center">

                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="34-35">
                                    24</span>
                            </td>

                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb15" name="cid[]" value="25" onclick="isChecked(this.checked);" title="Checkbox for row 16" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=25&amp;extension=com_content">

                                    Plugins</a>
                                <p class="smallsub" title="sample-data-articles/joomla/extensions/plugins">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: plugins)							</p>
                            </td>
                            <td class="center">

                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb15','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb15','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="5"  class="text-area-order" />
                            </td>
                            <td class="center">

                                Public					</td>
                            <td class="center nowrap">
                                All										</td>
                            <td class="center">
                                <span title="36-37">
                                    25</span>
                            </td>

                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb16" name="cid[]" value="26" onclick="isChecked(this.checked);" title="Checkbox for row 17" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=26&amp;extension=com_content">
                                    Park Site</a>

                                <p class="smallsub" title="sample-data-articles/park-site">
                                    <span class="gtr">|&mdash;</span>															(<span>Alias</span>: park-site)							</p>
                            </td>
                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb16','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>

                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb16','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="2"  class="text-area-order" />
                            </td>
                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">

                                English (UK)										</td>
                            <td class="center">
                                <span title="40-49">
                                    26</span>
                            </td>
                        </tr>
                        <tr class="row1">
                            <td class="center">

                                <input type="checkbox" id="cb17" name="cid[]" value="27" onclick="isChecked(this.checked);" title="Checkbox for row 18" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=27&amp;extension=com_content">
                                    Park Blog</a>
                                <p class="smallsub" title="sample-data-articles/park-site/park-blog">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: park-blog)							</p>

                            </td>
                            <td class="center">
                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb17','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span>&#160;</span>
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb17','categories.orderdown')" title="Move Down"><span class="state downarrow"><span class="text">Move Down</span></span></a></span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />

                            </td>
                            <td class="center">
                                Public					</td>
                            <td class="center nowrap">
                                English (UK)										</td>
                            <td class="center">
                                <span title="41-42">
                                    27</span>

                            </td>
                        </tr>
                        <tr class="row0">
                            <td class="center">
                                <input type="checkbox" id="cb18" name="cid[]" value="28" onclick="isChecked(this.checked);" title="Checkbox for row 19" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=28&amp;extension=com_content">

                                    Photo Gallery</a>
                                <p class="smallsub" title="sample-data-articles/park-site/photo-gallery">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: photo-gallery)							</p>
                            </td>
                            <td class="center">

                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb18','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span><a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb18','categories.orderup')" title="Move Up"><span class="state uparrow"><span class="text">Move Up</span></span></a></span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="2"  class="text-area-order" />
                            </td>
                            <td class="center">

                                Public					</td>
                            <td class="center nowrap">
                                English (UK)										</td>
                            <td class="center">
                                <span title="43-48">
                                    28</span>
                            </td>

                        </tr>
                        <tr class="row1">
                            <td class="center">
                                <input type="checkbox" id="cb19" name="cid[]" value="72" onclick="isChecked(this.checked);" title="Checkbox for row 20" />					</td>
                            <td>
                                <span class="gi">|&mdash;</span><span class="gi">|&mdash;</span><span class="gi">|&mdash;</span>																			<a href="/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=72&amp;extension=com_content">

                                    Animals</a>
                                <p class="smallsub" title="sample-data-articles/park-site/photo-gallery/animals">
                                    <span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span><span class="gtr">|&mdash;</span>															(<span>Alias</span>: animals)							</p>
                            </td>
                            <td class="center">

                                <a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb19','categories.unpublish')" title="Unpublish Item"><span class="state publish"><span class="text">Published</span></span></a>					</td>
                            <td class="order">
                                <span>&#160;</span>
                                <span>&#160;</span>
                                <input type="text" name="order[]" size="5" value="1"  class="text-area-order" />
                            </td>
                            <td class="center">
                                Public					</td>

                            <td class="center nowrap">
                                English (UK)										</td>
                            <td class="center">
                                <span title="44-45">
                                    72</span>
                            </td>
                        </tr>
                    </tbody>

                </table>
                <fieldset class="batch">
                    <legend>Batch process the selected categories</legend>
                    <p>If choosing to copy a category, any other actions selected will be applied to the copied category. Otherwise, all actions are applied to the selected category.</p>
                    <label id="batch-access-lbl" for="batch-access" class="hasTip" title="Set Access Level::Not making a selection will keep the original access levels when processing.">
                        Set Access Level
                    </label>
                    <select id="batch-access" name="batch[assetgroup_id]" class="inputbox">
                        <option value="">- Keep original Access Levels -</option>

                        <option value="1">Public</option>
                        <option value="2">Registered</option>
                        <option value="3">Special</option>
                        <option value="4">Customer Access Level (Example)</option>
                    </select>
                    <label id="batch-language-lbl" for="batch-language" class="hasTip" title="Set Language::Not making a selection will keep the original language when processing.">
                        Set Language
                    </label>

                    <select name="batch[language_id]" class="inputbox" id="batch-language-id">
                        <option value="">- Keep original Language -</option>
                        <option value="*">All</option>
                        <option value="en-GB">English (UK)</option>

                    </select>
                    <label id="batch-choose-action-lbl" for="batch-category-id">
                        Select Category for Move/Copy		</label>
                    <fieldset id="batch-choose-action" class="combo">
                        <select name="batch[category_id]" class="inputbox" id="batch-category-id">

                            <option value="">Select</option>
                            <option value="14">Sample Data-Articles</option>
                            <option value="19">- Joomla!</option>
                            <option value="20">- - Extensions</option>
                            <option value="21">- - - Components</option>
                            <option value="22">- - - Modules</option>
                            <option value="64">- - - - Content Modules</option>
                            <option value="65">- - - - User Modules</option>

                            <option value="66">- - - - Display Modules</option>
                            <option value="67">- - - - Utility Modules</option>
                            <option value="75">- - - - Navigation Modules</option>
                            <option value="23">- - - Templates</option>
                            <option value="69">- - - - Beez 20</option>
                            <option value="70">- - - - Beez5</option>
                            <option value="68">- - - - Atomic</option>
                            <option value="24">- - - Languages</option>
                            <option value="25">- - - Plugins</option>

                            <option value="26">- Park Site</option>
                            <option value="27">- - Park Blog</option>
                            <option value="28">- - Photo Gallery</option>
                            <option value="72">- - - Animals</option>
                            <option value="73">- - - Scenery</option>
                            <option value="29">- Fruit Shop Site</option>
                            <option value="30">- - Growers</option>
                            <option value="76">- - Recipes</option>
                            <option value="9">Uncategorised</option>

                            <option value="1">Add to root</option>
                        </select>

                        <input type="radio" name="batch[move_copy]" id="batch[move_copy]c" value="c"  />
                        <label for="batch[move_copy]c" id="batch[move_copy]c-lbl" class="radiobtn">Copy</label>
                        <input type="radio" name="batch[move_copy]" id="batch[move_copy]m" value="m"  checked="checked" />
                        <label for="batch[move_copy]m" id="batch[move_copy]m-lbl" class="radiobtn">Move</label>
                    </fieldset>

                    <button type="submit" onclick="submitbutton('category.batch');">

                        Process	</button>
                    <button type="button" onclick="document.id('batch-category-id').value='';document.id('batch-access').value='';document.id('batch-language-id').value=''">
                        Clear	</button>
                </fieldset>

                <div>
                    <input type="hidden" name="extension" value="com_content" />
                    <input type="hidden" name="task" value="" />
                    <input type="hidden" name="boxchecked" value="0" />

                    <input type="hidden" name="filter_order" value="a.lft" />
                    <input type="hidden" name="filter_order_Dir" value="asc" />
                    <input type="hidden" name="original_order_values" value="1,1,1,1,2,1,2,3,4,5,3,1,2,3,4,5,2,1,2,1" />
                    <input type="hidden" name="c978cef3fefdcfc5320d05e605203080" value="1" />	</div>
            </form>

            <div class="clr"></div>
        </div>
    </div>