<?php 
$content = (isset($this->article->fulltext)) ? str_replace(array("\s", "\n", "\r"), '', $this->article->fulltext) : '';
$introText = (isset($this->article->introtext)) ? str_replace(array("\s", "\n", "\r"), '', $this->article->introtext) : '';       
 ?>

<?php $this->headScript()->captureStart() ?>
dojo.addOnLoad(function() {
   var mainEditor = new im.imRichEditor({editorNode: "articletext"}, 'articletext');
     var introEditor = new im.imRichEditor({editorNode: "introtext", theme: "simple", toolbar_location:"top"}, 'introtext');
     dojo.addOnLoad(function() {
     introEditor.setValue("<?php echo addslashes($introText); ?>");
         mainEditor.setValue('<?php echo addslashes($content); ?>');
         
     });
    
});


<?php $this->headScript()->captureEnd() ?>

 <div id="content-box">
<odoc:include type="Sticky" name="Toolbar" function="toolbar" params="{'save': 'save', 'saveAndClose' : 'saveAndClose', 'cancel': 'cancel', 'help' : 'help','class': 'article-add', 'pagetitle' : 'addNewArticle', 'formID' : 'createarticleForm' }" /> 
<!-- <div class="pagetitle icon-48-article-add"><h2>Article Manager: Add New Article</h2></div> -->
<div id='responseMsg'></div>
 <odoc:include type="Sticky" name="MessageQueue" />
 
<div id="element-box">
    <div class="m">


        <form action="/cms/process" method="post" name="createarticleForm" id="createarticleForm" class="form-validate">
            <div class="width-60 fltlft">
                <fieldset class="adminform">
                    <legend>New Article</legend>
               
                    <ul class="adminformlist">
                        <li><label id="iform_title-lbl" for="iform_title" class="hasTip required" title="Title::Title">Title<span class="star"></span></label>				
                            <input type="text" name="title" id="iform_title" value="<?php echo @$this->article->title ?>" class="inputbox required" size="45"/>
                          
                        </li>
                        <li><label id="iform_state-lbl" for="iform_state" class="hasTip" title="Status::Set publication status.">Status</label>				
                            <select id="iform_state" name="published" class="inputbox" size="1">
                                <?php 
                                    $options = array( '0' => 'Unpublished',
                                                      '1' => 'Published',   
                                                      '2' => 'Archived',
                                                      '-2' => 'Trashed',
                                                     );
                                
                                 foreach ($options as $k =>$v) : 
                                     if(@$this->article->published == $k ) : ?>
                                         <option value="<?php echo $k ?>" selected="selected"><?php echo $v ?></option>
                                     <?php  elseif (!@$this->article->published && $v == 'Published') :  ?>
                                       <option value="<?php echo $k ?>" selected="selected"><?php echo $v ?></option>   
                                     <?php  else : ?>
                                      <option value="<?php echo $k ?>" ><?php echo $v ?></option>   
                                     <?php endif;
                                  endforeach;
                                  ?>
                          
                            </select>
                        </li>

                        <li><label id="iform_access-lbl" for="iform_access" class="hasTip" title="Access::The access level group that is allowed to view this item.">Access</label>
                            <select id="iform_access" name="access"  class="inputbox" size="1">

                                <option value="1" selected="selected">Public</option>
                                <option value="2">Registered</option>
                                <option value="3">Special</option>
                                <option value="4">Customer Access Level (Example)</option>
                            </select>
                        </li>

                       
                        
                        <li><label id="iform_language-lbl" for="iform_language" class="hasTip" title="Language::The language that the article is assigned to.">Language</label>
                            <select id="iform_language" name="language" class="inputbox">
                                <option value="en">English</option>
                            </select>

                        </li>
                        <li><label id="iform_alias-lbl" for="iform_alias" class="hasTip" title="ALIAS:: It an alternative way to access your blog or article instead of the id. dash is used to replace spaces">Alias</label>	
                            <input type="text" name="alias" id="iform_id" value="<?php echo @$this->article->alias ?>" class="readonly" size="45" readonly="readonly"/>
                        </li>
                        <li><label id="iform_id-lbl" for="iform_id" class="hasTip" title="ID::Record number in the database">ID</label>	
                            <input type="text" name="id" id="iform_id" value="<?php echo @$this->article->id ?>" class="readonly" size="45" readonly="readonly"/>
                        </li>
                    </ul>

                    <div class="clr"></div>
                    <label id="iform_articletext-lbl" for="iform_articletext" class="hasTip" title="Article Text::Enter the article content in the text-area">Content</label>	
                    
                    <div class="clr"></div>
                       <textarea name="fulltext" id="articletext" cols="0" rows="0" style="width:100%; height:400px;" ></textarea> 
                      </fieldset>

            </div>

            <div class="width-40 fltrt">
                <div id="content-sliders-" class="pane-sliders"><div style="display:none;"><div>
                        </div></div><div class="panel"><h3 class="pane-toggler title" id="publishing-details"><a href="javascript:void(0);"><span>Publishing Options</span></a></h3><div class="pane-slider content">			<fieldset class="panelform">
                                 <?php $options = isset($this->article->attribs) ? str_replace('"' , "'" , @$this->article->attribs ) : '{}'; ?>   
                               <odoc:include type="Sticky" name="Template" function="getPublishingOptions" params="{'contentType' : 'article', 'values' : <?php echo $options ?> }" /> 

                            </fieldset>

                        </div></div>
                    
                    <div class="panel"><h3 class="pane-toggler title" id="meta-options"><a href="javascript:void(0);"><span>Article Introduction</span></a></h3><div class="pane-slider content">			<fieldset class="panelform">
                               <li><label id="jform_metadesc-lbl" for="jform_metadesc" class="hasTip" 
                                          title="Meta Description::An optional paragraph to be used as the description of the page in the HTML output. 
                                          This will generally display in the results of search engines.">Article Introduction</label>	
                                    <textarea name="introtext" id="introtext" cols="30" rows="3" class="inputbox"><?php echo @$this->article->introtext ?></textarea>  
                                    <div id="tEditor">

                               </li>
                            </fieldset>

                        </div></div>
                    
                    
                    <div class="panel"><h3 class="pane-toggler title" id="meta-options"><a href="javascript:void(0);"><span>Metadata Options</span></a></h3>
                        <div class="pane-slider content">			<fieldset class="panelform">
                                <ul class="adminformlist">

                                    <li><label id="iform_metadesc-lbl" for="iform_metadesc" class="hasTip" title="Meta Description::An optional paragraph to be used as the description of the page in the HTML output. This will generally display in the results of search engines.">Meta Description</label>	
                                        <textarea name="metadesc" id="iform_metadesc" cols="30" rows="3" class="inputbox"><?php echo @$this->article->metadesc ?></textarea></li>

                                    <li><label id="iform_metakey-lbl" for="jform_metakey" class="hasTip" title="Meta Keywords::An optional comma-separated list of keywords and/or phrases to be used in the HTML output.">Meta Keywords</label>	
                                        <textarea name="metakey" id="iform_metakey" cols="30" rows="3" class="inputbox"><?php echo @$this->article->metakey ?></textarea></li>


                                    <li>
                                        <label id="iform_metadata_robots-lbl" for="iform_metadata_robots" class="hasTip" title="Robots::Robots Instructions">Robots</label>				
                                            <select id="iform_metadata_robots" name="metadata[robots]">

                                            <option value="" selected="selected">Use Global</option>
                                            <option value="index, follow">Index, Follow</option>
                                            <option value="noindex, follow">No index, follow</option>
                                            <option value="index, nofollow">Index, No follow</option>
                                            <option value="noindex, nofollow">No index, no follow</option>
                                        </select>
                                    </li>

                                   </ul>
                            </fieldset>

                        </div></div></div>	</div>
                <input type="hidden" name="content_type" id="content_type" value="<?php echo @$this->contentType ?>" />
            <div class="clr"></div>
        </form>

            <noscript>
            Warning! JavaScript must be enabled for proper operation of the Administrator backend.		</noscript>
    </div>
