<?php $this->headScript()->captureStart() ?>
window.addEvent('domready', function(){ new Fx.Accordion($$('div#panel-sliders.pane-sliders > .panel > h3.pane-toggler'), $$('div#panel-sliders.pane-sliders > .panel > div.pane-slider'), {onActive: function(toggler, i) {toggler.addClass('pane-toggler-down');toggler.removeClass('pane-toggler');i.addClass('pane-down');i.removeClass('pane-hide');Cookie.write('jpanesliders_panel-sliders',$$('div#panel-sliders.pane-sliders > .panel > h3').indexOf(toggler));},onBackground: function(toggler, i) {toggler.addClass('pane-toggler');toggler.removeClass('pane-toggler-down');i.addClass('pane-hide');i.removeClass('pane-down');if($$('div#panel-sliders.pane-sliders > .panel > h3').length==$$('div#panel-sliders.pane-sliders > .panel > h3.pane-toggler').length) Cookie.write('jpanesliders_panel-sliders',-1);},duration: 300,opacity: false,alwaysHide: true}); });
  
<?php $this->headScript()->captureEnd() ?>

<div id="header-box">
    <div id="module-status">
        <span class="loggedin-users">None Logged-in frontend</span><span class="backloggedin-users">1 Logged-in backend</span><span class="no-unread-messages"><a href="/cms/messages">No messages</a></span>

        <span class="viewsite"><a href="http://joomla/" target="_blank">View Site</a></span><span class="logout"><a href="/cms/logout">Log out</a></span>		</div>
    <div id="module-menu">
         <odoc:include type="Sticky" name="MainMenu"  />
    </div>
    <!-- end menu -->
    <div class="clr"></div>
</div>

<div id="content-box">
    <odoc:include type="Sticky" name="MessageQueue" />
    <div id="element-box">
        <div id="system-message-container"> </div>
        <div class="m">
            <div class="adminform">
                <div class="cpanel-left"> 
                    <odoc:include type="Sticky" name="Cpanel" function="leftCpanel" options="top" />                   
                </div>
                <div class="cpanel-right">                    
                    <odoc:include type="Sticky" name="Cpanel" function="rightCpanel" options="top" />
                </div>
            </div>
            <div class="clr"></div>
        </div>