<?php
// no direct access
var_dump($template);
$fontstyle = 'f-default';
$tstyle = 'light-green';
$mtype = 'module';
$subnav = '';
// these must come below because the styles can be overloaded
$body_style = 'light';

?>

<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="<?php echo $this->template->language; ?>" >
    <head>
<?php echo $this->headTitle() . PHP_EOL; ?>
        <?php echo $this->headMeta()->setCharset('utf-8') . PHP_EOL; ?>              
        <?php echo $this->headScript() . PHP_EOL; ?>
 <BASE href="http://core.tradingingredients.com">  
        <link href="/media/site/css/template.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/media/site/css/light.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/media/site/css/rokmoomenu.css" media="screen" rel="stylesheet" type="text/css" >
<?php echo $this->headLink() . PHP_EOL; ?>
        <style type="text/css">
            div.wrapper,#main-body-bg { margin: 0 auto; width: <?php echo $template->width ?>px;padding:0;}
            #inset-block-left { width:0px;padding:0;}
            #inset-block-right { width:0px;padding:0;}
            #maincontent-block { margin-right:0px;margin-left:0px;}
            a, legend, #main-body ul.menu li a:hover, #main-body ul.menu li.parent li a:hover, #main-body ul.menu li.parent ul li.parent ul li a:hover, #main-body ul.menu li.active a, #main-body ul.menu li.parent li.active a, #main-body ul.menu li.parent li.parent li.active a, #main-body ul.menu li.cat-open a, #main-body ul.menu li.parent li.cat-open a, #main-body ul.menu li.parent li.parent li.cat-open a, .roktabs-wrapper .roktabs-links ul li.active span, .color h3 span, #vmMainPage span.catbar-text h3, div.pathway a {color: #cf230b;}
            #page-bg, .roktabs-wrapper .roktabs-links ul li.active span {border-top: 3px solid #cf230b;}
            .tabs-bottom .roktabs-links ul li.active span {border-bottom: 3px solid #cf230b;border-top: 0;}
            #rt-top-surround, #roksearch_results,#rt-top-surround #rokajaxsearch .rokajaxsearch .inputbox {background-color:#191919;}
            #rt-top a, #rt-header a, .menutop li > .item, #rt-top-surround .roktabs-wrapper .roktabs-links ul li.active span  {color:#fff;}
            #rt-footer-surround,#rt-footer-surround #rokajaxsearch .rokajaxsearch .inputbox {background-color:#191919;}
            #rt-footer-surround a, #rt-bottom a, #rt-footer a,#rt-footer-surround .roktabs-wrapper .roktabs-links ul li.active span {color:#ccc;}

            body #rt-logo {width:200px;height:55px;}
        </style>

    </head>
    <body id="ff-mynxx" class="<?php echo $fontstyle; ?> <?php echo $tstyle; ?> <?php echo $body_style; ?> iehandle tundra" >
        <div class="topblock-overlay-dark" id="rt-top-surround">
            <div id="rt-drawer">
                <div class="rt-container">
                    <div class="clear"></div>
                </div>
            </div>
            
            <div id="rt-top-pattern">
                <div id="rt-header">
                    <div class="rt-container">
                        <div class="rt-grid-6 rt-alpha">
                            <div class="rt-block logo-block">
                                <a id="rt-logo" href="/joomla15/halcyon/"></a>
                            </div>

                        </div>
                        <div class="rt-grid-6 rt-omega">
                            <div class="rt-block">
                                <div class="module-surround">
                                    <div class="module-content">
                                        <div class="rt-menubar">
                                        
                                           <?php if ($this->template->showUserTopMenu == 'true') : ?>
                                             <odoc:include type="Sticky" name="Blocks" function="userTopMenu" />
                                            <?php endif ?>
                                            <?php if ($this->template->showTopMenu == 'true') : ?>
                                             <odoc:include type="Sticky" name="Blocks" function="topMenu" />
                                            <?php endif ?>
                                        <div class="arrow-indicator" style="left: 414px;"></div>
                                    </div>					<div class="clear"></div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
              
            </div>
            <div id="rt-subnavigation" style="height: 37px; overflow: hidden;">
                <div class="rt-container">
                    <div class="rt-grid-12 rt-alpha rt-omega">
                        <div class="rt-block menu-block">
                            <div class="rt-splicemenu-children">
                                <div class="rt-menubar">
                                    <div class="rt-menubar2">
                                        <ul class="parentitem11 parent menu level1" style="position: absolute; display: inline-block; visibility: visible; opacity: 1;">
                                            <li class="item43">
                                                <a href="/joomla15/halcyon/?presets=preset1" class="orphan item">
                                                    <span>
                                                        Preset 1                                        </span>
                                                </a>
                                            </li>
                                            <li class="item44">
                                                <a href="/joomla15/halcyon/?presets=preset2" class="orphan item">
                                                    <span>
                                                        Preset 2                                        </span>
                                                </a>
                                            </li>
                                            <li class="item45">
                                                <a href="/joomla15/halcyon/?presets=preset3" class="orphan item">
                                                    <span>
                                                        Preset 3                                        </span>
                                                </a>
                                            </li>
                                            <li class="item46">
                                                <a href="/joomla15/halcyon/?presets=preset4" class="orphan item">
                                                    <span>
                                                        Preset 4                                        </span>
                                                </a>
                                            </li>
                                            <li class="item47">
                                                <a href="/joomla15/halcyon/?presets=preset5" class="orphan item">
                                                    <span>
                                                        Preset 5                                        </span>
                                                </a>
                                            </li>
                                            <li class="item48">
                                                <a href="/joomla15/halcyon/?presets=preset6" class="orphan item">
                                                    <span>
                                                        Preset 6                                        </span>
                                                </a>
                                            </li>
                                            <li class="item49">
                                                <a href="/joomla15/halcyon/?presets=preset7" class="orphan item">
                                                    <span>
                                                        Preset 7                                        </span>
                                                </a>
                                            </li>
                                            <li class="item50">
                                                <a href="/joomla15/halcyon/?presets=preset8" class="orphan item">
                                                    <span>
                                                        Preset 8                                        </span>
                                                </a>
                                            </li>
                                            <li class="item51">
                                                <a href="/joomla15/halcyon/?presets=preset9" class="orphan item">
                                                    <span>
                                                        Preset 9                                        </span>
                                                </a>
                                            </li>
                                            <li class="item53">
                                                <a href="/joomla15/halcyon/?presets=preset10" class="orphan item">
                                                    <span>
                                                        Preset 10                                        </span>
                                                </a>
                                            </li>
                                        </ul>
                                        
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>

                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>

        <div id="page-bg">
            <!--Begin Header-->
           <!-- <div id="header">
                <div class="wrapper">
<?php if (isset($this->template->moduleCount->advertisement)) : ?>
                        <div class="ad-module-top">
                            <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name' :'advertisement'}" />
                        </div>
<?php endif; ?>

<?php if ($this->template->showLogo == 'false') : ?>
                    <div class="logo-module">
                        <odoc:include type="Sticky" name="Blocks" function="logo" />
                    </div>
<?php elseif ($this->template->showLogo == "true") : ?>
                    <a href="<?php echo $this->baseurl; ?>" id="logo">
<?php if ($this->template->showLogoSlogan == "true") : ?>
                            <span class="logo-text"><?php echo $this->template->logoSlogan; ?></span>
<?php endif; ?>
                    </a>
<?php endif; ?>
                    <?php if ($mtype != "none") : ?>
                            <div id="horiz-menu" class="<?php echo $mtype; ?>">
<?php if ($mtype != "module") : ?>
                        <?php echo $topnav; ?>
                        <?php else: ?>
                                    <odoc:include type="Sticky" name="Blocks" function="toolbar" />
<?php endif; ?>
                                </div>
<?php endif; ?>
                                <div class="clr"></div>
                            </div>
                        </div> -->
                        <!--End Header-->
                        <div class="wrapper">
                            <div id="main-body">
                                
                                                <div id="main-body-surround">
                                                    <div id="cart-panel-surround" class="png">
                                                        <div id="cart-panel" class="png"></div>
                                                    </div>

<?php if (isset($this->template->moduleCount->login)) : ?>
                                                        <div id="login-panel-surround" class="png">
                                                            <div id="login-panel" class="png">
                                                                <div id="login-module">
                                                                    <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name' :'login'}" />
                                                                </div>
                                                            </div>
                                                        </div>
<?php endif; ?>
                                                                <!--Begin Showcase-->

<?php if (isset($this->template->moduleCount->scroller)) : ?>
                                                                    <div class="showcase-surround">
                                                                        <div class="show-br"></div>
                                                                        <div id="showcase">
                                                                            <div id="showcase2">
                                                                                <odoc:include type="Sticky" name="Blocks" function="scroller" params="{'style': 'scroller'}" />
                                                                            </div>
                                                                        </div>
                                                                        <div class="show-bl"></div>
                                                                    </div>
<?php endif; ?>
                                                                    <!--End Showcase-->


                                                                    <div class="sec-div"></div>

                                                                    <!--Begin Main Content Block-->

                                                                    <div id="main-content-surround">
                                                                        <div id="main-content" class="<?php echo $this->setUp->colMode; ?>">
                                                                            <div class="colmask leftmenu">
                                                                                <div class="colmid">
                                                                                    <div class="colright">
                                                                                        <!--Begin col1wrap -->
                                                                                        <div class="col1wrap">
                                                                                            <div class="col1pad">
                                                                                                <div class="col1">
                                                                                                    <div id="maincol2">
                                                                                                        <!-- get the PHTML -->
                                                                                                        <div class="maincol2-padding">


<?php if (isset($this->template->moduleCount->user1) || isset($this->template->moduleCount->user2) || isset($this->template->moduleCount->user3)) : ?>
                                                                                                                <div id="mainmodules2" class="spacer<?php echo $this->setUp->mainUserWidth; ?>">

                                                                            <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name':'topBlock' , 'style' : 'main'}" />


                                                                        </div>
<?php endif; ?>
                                                                <?php if (isset($this->template->moduleCount->breadcrumb)) : ?>
                                                                            <div id="breadcrumbs">
                                                                                <div class="moduletable">
                                                                                    <h3>Breadcrumbs</h3>
                                                                                    <span class="breadcrumbs pathway">
                                                                                        <odoc:include type="Sticky" name="Blocks" function="breadcrumb" />
                                                                                    </span>
                                                                                </div>
                                                                            </div>
<?php endif; ?>

                                                                            <div>
<?php if (isset($this->template->moduleCount->inset)) : ?>
                                                                                    <div id="inset-block-right"><div class="right-padding">
                                                                                            <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'inset'}" />
                                                                                        </div></div>
<?php endif; ?>
                                                                    <?php if (isset($this->template->moduleCount->inset2)) : ?>
                                                                                    <div id="inset-block-left"><div class="left-padding">
                                                                                            <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'inset2' }" />
                                                                                        </div></div>
<?php endif; ?>
                                                                                    <div id="maincontent-block">
                                                                                        <odoc:include type="Sticky" name="MessageQueue" />
                                                                                        <div id="page" class="full-article">
<?php echo $this->content; ?>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="clr"></div>
<?php if (isset($this->template->moduleCount->user4) || isset($this->template->moduleCount->user5) || isset($this->template->moduleCount->user6)) : ?>
                                                                            <div id="mainmodules2" class="spacer<?php echo $this->setUp->mainUser2Width; ?>">
                                                                                            <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'middleMain' , 'style' : 'main'}" />
                                                                                        </div>
<?php endif; ?>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <!--End col1wrap -->
                                                                    <!--Begin col2 -->
<?php if (@$this->setUp->leftColumnWidth != 0) : ?>
                                                                        <div class="col2">
                                                                            <div id="leftcol">
                                                                                <div id="leftcol-bg">
<?php if (isset($this->template->moduleCount->searchLeft)) : ?>
                                                                                                            <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'search'}" />
<?php endif; ?>
                                                        <?php if ($subnav == "leftcol") : ?>
                                                                                                    <div class="sidenav-block">
<?php echo $subnav; ?>
                                                                                                    </div>
<?php endif; ?>
                                                                                                <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'left'}" />

                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
<?php endif; ?> 
                                                                                        <!---End col2 -->
                                                                                        <!--Begin col3 -->
<?php if (@$this->setUp->rightColumnWidth != 0) : ?>
                                                                                                        <div class="col3">
                                                                                                            <div id="rightcol">
<?php if (isset($this->template->moduleCount->searchRight)) : ?>                                                        
                                                                                                                    <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'search'}" />
<?php endif; ?>
                                                    <?php if ($subnav == "rightcol") : ?>
                                                                                                                <div class="sidenav-block">
<?php echo $subnav; ?>
                                                                                                                </div>
<?php endif; ?>                                                     
                                                                                                            <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'right'}" />
                                                                                                        </div>
                                                                                                    </div>
<?php endif; ?> 
                                                                                                        <!--End col3-->
                                                                                                    </div>
                                                                                                </div>
                                                                                            </div>
                                                                                        </div>
                                                                                        <div class="corner" id="bl"></div>
                                                                                        <div class="corner" id="br"></div>
                                                                                        <div class="corner" id="tl"></div>
                                                                                        <div class="corner" id="tr"></div>
                                                                                    </div>


                                                                                    <!--End Main Content Block-->
                                                                                </div>
                                                                                <!--Begin Bottom Main Modules-->
<?php if (isset($this->template->moduleCount->user7) || isset($this->config->template->moduleCount->user8) || isset($this->template->moduleCount->user9)) : ?>
                                                                                            <div class="sec-div"></div>
                                                                                            <div id="bottom-main">
                                                                                                <div id="bottom-main2">
                                                                                                    <div id="mainmodules3" class="spacer<?php echo $this->setUp->mainUser3Width; ?>">
                                                                                                                                <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'bottomMain', 'style' : 'main'}" />
                                                                                                                            </div>
                                                                                                                        </div>
                                                                                                                        <div class="bottom-bl"></div>
                                                                                                                        <div class="bottom-br"></div>
                                                                                                                        <div class="bottom-tl"></div>
                                                                                                                        <div class="bottom-tr"></div>
                                                                                                                    </div>
<?php endif; ?>
                                                                                                                    <!--End Bottom Main Modules-->
                                                                                                                    <div class="sec-div"></div>

                                                                                                                    <!--End Bottom Bar-->
                                                                                                                    <!--Begin Bottom Section-->
<?php if (isset($this->template->bottom) || isset($this->template->bottom2) || isset($this->template->bottom3)) : ?>
                                                                                                                        <div id="bottom">
                                                                                                                            <div id="mainmodules4" class="spacer<?php echo $this->setUp->mainBottomWidth; ?>">
                                                                                                                                <div class="block <?php echo @$this->template->moduleCount->bottomClass; ?>">
                                                                                                                                    <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'bottomLow'}" />
                                                                                                                                </div>
                                                                                                                            </div>
                                                                                                                        </div>
<?php endif; ?>
                    <?php if (isset($this->template->moduleCount->bottomMenu) || $this->template->showBottomLogo == "true") : ?>
                                                                                                                           <!-- <div id="footer">
                                                                                                                                <div id="footer2">
                                                                                                                                    <div id="footer3">
<?php if (@$this->template->show_bottomlogo == "true") : ?>
                                                                                                                                            <a href="<?php echo $this->baseurl; ?>" id="bottom-logo"></a>
<?php endif; ?>
                                <?php if (isset($this->template->moduleCount->bottomMenu)) : ?>
                                                                                                                                    <div id="bottom-menu">
                                                                                                                                        <odoc:include type="Sticky" name="Blocks" function="bottomMenu"  />
                                                                                                                                    </div>
<?php endif; ?>
                                                                                                                                </div>
                                                                                                                            </div>
                                                                                                                        </div> -->
<?php endif; ?>



                                                                                                                      <!--  <div id="footerbar">
                                                                                                                            <div id="footerbar2">
                                                                                                                                <div id="footerbar3">
<?php if ($this->template->showCopyright == "true") : ?>
                                                                                                                                                    <div class="copyright-block">
                                                                                                                                                        <a href="http://infosyspro.com.au/" title="Infosyspro" id="rocket"></a>
                                                                                                                                                        <div id="copyright">
                                                                                                                                                            &copy; Infosyspro 2011 - <?php echo date('Y') ?>
                                                                                                                                            </div>
                                                                                                                                        </div>
<?php else: ?>
                                                                                                                                            <div class="footer-mod">
                                                                                                                                                <odoc:include type="Sticky" name="Blocks" function="getBlock" params="{'name': 'footer'}" />
                                                                                                                                            </div>
<?php endif; ?>
                            </div>
                        </div>
                    </div> -->
                    <!--End Bottom Section-->
                </div>
            </div>
        </div>

        <div class="bottomblock-overlay-dark" id="rt-footer-surround">
            <div class="rt-container">
                <div id="rt-bottom">
                    <div class="rt-grid-8 rt-alpha">
                        <div class="rt-block">
                            <div class="module-surround">
                                <div class="module-content">
                                    <div class="floatleft">
                                        <div class="smallmarginbottom"><em class="bold nobold">Products</em></div>
                                        <ul class="dots nomarginbottom">
                                            <li><a href="#"><em class="nobold normal">Laptops</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Desktop PC</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Printers</em></a></li>
                                            <li class="nomarginbottom"><a href="#"><em class="nobold normal">Tablets</em></a></li>
                                        </ul>
                                    </div>
                                    <div class="floatleft largemarginleft">
                                        <div class="smallmarginbottom">&nbsp;</div>
                                        <ul class="dots nomarginbottom">
                                            <li><a href="#"><em class="nobold normal">Monitors</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Keyboards</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Speakers</em></a></li>
                                            <li class="nomarginbottom"><a href="#"><em class="nobold normal">Cameras</em></a></li>
                                        </ul>
                                    </div>
                                    <div class="floatleft largemarginleft">
                                        <div class="smallmarginbottom">&nbsp;</div>
                                        <ul class="dots nomarginbottom">
                                            <li><a href="#"><em class="nobold normal">Storage</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Phones</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Accessories</em></a></li>
                                            <li class="nomarginbottom"><a href="#"><em class="nobold normal">Seasonal</em></a></li>
                                        </ul>
                                    </div>
                                    <div class="floatleft nomarginright largemarginleft">
                                        <div class="smallmarginbottom">&nbsp;</div>
                                        <ul class="dots nomarginbottom">
                                            <li><a href="#"><em class="nobold normal">Delivery</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Refunds</em></a></li>
                                            <li><a href="#"><em class="nobold normal">Careers</em></a></li>
                                            <li class="nomarginbottom"><a href="#"><em class="nobold normal">Sitemap</em></a></li>
                                        </ul>
                                    </div>						<div class="clear"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="rt-grid-4 rt-omega">
                        <div class="rt-block">
                            <div class="module-surround">
                                <div class="module-content">
                                    <div class="floatleft">
                                        <div class="smallmarginbottom"><em class="bold nobold">Demo Information</em></div>
                                        <a class="nobold">All demo content is for <strong>sample</strong> purposes only, intended to represent a live site. All images are the copyright of their respective owners. Please download the <strong>RocketLauncher</strong> pack to install a copy of the demo.</a>
                                    </div>						<div class="clear"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="clear"></div>
                </div>
                <div id="rt-footer">
                    <div class="rt-grid-3 rt-alpha">
                        <div class="rt-block">
                            <div class="module-surround">
                                <div class="module-content">
                                    <span class="text-icon phone smallmarginbottom">+1 (555) 555-5555 / 5556</span>						<div class="clear"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="rt-grid-3">
                        <div class="rt-block">
                            <div class="module-surround">
                                <div class="module-content">
                                    <span class="text-icon email smallmarginbottom">noreply@rockettheme.com</span>						<div class="clear"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="rt-grid-3">
                        <div class="rt-block">
                            <div class="module-surround">
                                <div class="module-content">
                                    <span class="text-icon facebook smallmarginbottom">facebook.com/rockettheme</span>						<div class="clear"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="rt-grid-3 rt-omega">
                        <div class="rt-block">
                            <div class="module-surround">
                                <div class="module-content">
                                    <span class="text-icon twitter smallmarginbottom">@rockettheme #halcyon</span>						<div class="clear"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>


        <div id="rt-copyright">
            <div class="rt-container">
                <div class="rt-grid-4 rt-alpha">
                    <div class="rt-block">
                        <span class="copytext">Designed by RocketTheme</span>
                    </div>

                </div>
                <div class="rt-grid-4">
                    <div class="rt-block totop-block">
                        <a id="gantry-totop" href="#" style="outline: medium none;"><span class="totop-desc">Back to Top</span></a>
                    </div>

                </div>
                <div class="rt-grid-4 rt-omega">
                    <div class="rt-block">
                        <div id="developed-by">
                            <a id="rocket" title="rockettheme.com" href="http://www.rockettheme.com/"></a>
                        </div>
                    </div>

                </div>
                <div class="clear"></div>
            </div>
        </div>


    </body>
</html>