<?php echo $this->doctype()?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() . PHP_EOL;  ?>
    <?php echo $this->headMeta()->setCharset('UTF-8') . PHP_EOL; ?>
    <?php echo $this->headScript() . PHP_EOL; ?>
    <?php echo $this->headLink() . PHP_EOL; ?>
</head>
<body>
	<div id="border-top" class="h_blue">
		<span class="title"><a href="index.php"><?php echo $this->sitename . " Administration"; ?></a></span>
	</div>


<?php echo $this->content; ?>

    <div id="footer">
		<p class="copyright">
			<a href="http://www.joomla.org">Joomla!&#174;</a> later <a
				href="http://www.gnu.org/licenses/gpl-2.0.html">GNU General Public
				License</a>.
		</p>
	</div>
	<div id="bottom">
		test
		<odoc:include type="Sticky" name="Cpanel" />
	</div>

</body>
</html>
